apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: output-artifact-gcs
spec:
  entrypoint: output-artifact-gcs
  templates:
    - name: output-artifact-gcs  
      container:
        image: google/cloud-sdk:latest
        command: [sh, -c]
        args: ["git lfs clone https://huggingface.co/tiiuae/falcon-40b-instruct --depth 1"]
      outputs:
        artifacts:
          - name: files
            path: /
            gcs:
              bucket: llm_bucket_789
              key: path/in/bucket/falcon-40b-instruct.tgz
              serviceAccountKeySecret:
                name: my-gcs-credentials
                key: serviceAccountKey